# Generated by Django 2.1 on 2018-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoMascota', models.ImageField(upload_to='')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('razaMascota', models.CharField(max_length=20)),
                ('descripcionMascota', models.CharField(max_length=20)),
                ('estadoMascota', models.CharField(max_length=20)),
            ],
        ),
    ]
