# Generated by Django 2.1 on 2018-11-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rutPersona', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passwordPersona', models.CharField(max_length=10)),
                ('nombrePersona', models.CharField(max_length=10)),
                ('emailPersona', models.CharField(max_length=10)),
                ('viviendaPersona', models.CharField(max_length=40)),
            ],
        ),
    ]
